version: '3.8'

networks:
  nutsnbolts-net:
    external: true

services:
  nuts:
    hostname: nuts
    networks:
      - nutsnbolts-net
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/app
    environment:
      INTERNAL_PORT: 5000
      WORKERS: 2
      DB_HOST: nutsnbolts-db
      DB_PORT: 5432
      DB_NAME: nutsnbolts
      DB_USER: nutsnbolts
      DB_PASSWORD: nutsnbolts
      DOCKER_CONTAINER: YES
