version: '3.8'

services:
  nutsnbolts-db:
    build: .
    ports:
      - "55432:5432"
    environment:
      - POSTGRES_DB=nutsnbolts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
