version: '3.8'

services:
  apigateway:
    image: apigateway-service:latest
    command: /app/run.sh
    environment:
      - INTERNAL_PORT=${APIGATEWAY_PORT}
      - EXTERNAL_PORT=80
      - NUTS_HOST=http://localhost:${NUTS_PORT}
      - BOLTS_HOST=http://localhost:${BOLTS_PORT}
      - WORKERS=2
    network_mode: "host"
    hostname: localhost
  nuts:
    image: nuts-service:latest
    command: /app/run.sh
    environment:
      - INTERNAL_PORT=${NUTS_PORT}
      - WORKERS=2
      - DB_HOST=localhost
      - DB_PORT=${POSTGRES_PORT}
      - DB_NAME=nutsnbolts
      - DB_USER=nutsnbolts
      - DB_PASSWORD=nutsnbolts
    network_mode: "host"
    hostname: localhost
    depends_on:
      - nutsnbolts-db
  bolts:
    image: bolts-service:latest
    command: /app/run.sh
    environment:
      - INTERNAL_PORT=${BOLTS_PORT}
      - WORKERS=2
      - DB_HOST=localhost
      - DB_PORT=${POSTGRES_PORT}
      - DB_NAME=nutsnbolts
      - DB_USER=nutsnbolts
      - DB_PASSWORD=nutsnbolts
    network_mode: "host"
    hostname: localhost
    depends_on:
      - nutsnbolts-db
  nutsnbolts-db:
    image: nutsnbolts-db:latest
    environment:
      - POSTGRES_DB=nutsnbolts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    network_mode: "host"
    hostname: localhost
    command: -p ${POSTGRES_PORT}  # internal port postgres is running on
