version: '3.8'

services:
  apigateway:
    image: apigateway-service:latest
    command: /app/run.sh
    environment:
      - INTERNAL_PORT=5000
      - EXTERNAL_PORT=80
      - NUTS_HOST=http://localhost:5001
      - BOLTS_HOST=http://localhost:5002
      - WORKERS=2
    network_mode: "host"
    hostname: localhost
  envoy:
    image: envoyproxy/envoy:v1.22-latest
    network_mode: "host"
    hostname: localhost
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
  nuts:
    image: nuts-service:latest
    command: /app/run.sh
    environment:
      - INTERNAL_PORT=5001
      - WORKERS=2
      - DB_HOST=localhost
      - DB_PORT=55432
      - DB_NAME=nutsnbolts
      - DB_USER=nutsnbolts
      - DB_PASSWORD=nutsnbolts
    network_mode: "host"
    hostname: localhost
    depends_on:
      - nutsnbolts-db
  bolts:
    image: bolts-service:latest
    command: /app/run.sh
    environment:
      - INTERNAL_PORT=5002
      - WORKERS=2
      - DB_HOST=localhost
      - DB_PORT=55432
      - DB_NAME=nutsnbolts
      - DB_USER=nutsnbolts
      - DB_PASSWORD=nutsnbolts
    network_mode: "host"
    hostname: localhost
    depends_on:
      - nutsnbolts-db
  nutsnbolts-db:
    image: nutsnbolts-db:latest
    environment:
      - POSTGRES_DB=nutsnbolts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    network_mode: "host"
    hostname: localhost
    command: -p 55432  # internal port postgres is running on
